cls
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-01-Hello-World\HelloWorld" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-01-Hello-World\HelloWorldConfig" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-01-Hello-World\HelloWorldifParamHello" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-01-Hello-World\HelloWorldParamDiff" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-01-Hello-World\HelloWorldYAML" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-02-jQuery-AJAX-Extend-Parents\CallAJAXParent" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-02-jQuery-AJAX-Extend-Parents\jQueryAJAXAnchorNavigation" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-02-jQuery-AJAX-Extend-Parents\ThisAndExtendController" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-03-API=MySQL-Bitrix-Joomla\BitrixAPI" "en" "bitrix\modules\evnine\classes\general\"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-03-API=MySQL-Bitrix-Joomla\BitrixAPITwig" "en" "bitrix\modules\evnine\classes\general\"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-03-API=MySQL-Bitrix-Joomla\JoomlaAPI" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-03-API=MySQL-Bitrix-Joomla\MySQL" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-04-Validation-Errors-ExceptionThrow\ModelsMSGErrors" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-04-Validation-Errors-ExceptionThrow\ModelsMSGExceptionThrowError" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-04-Validation-Errors-ExceptionThrow\ModelsMSGInfo" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-04-Validation-Errors-ExceptionThrow\Validation" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-05-HREF-SEF-FORM\ExtendController-Method" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-05-HREF-SEF-FORM\Form" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-05-HREF-SEF-FORM\FormMultiMethodSumbit" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-05-HREF-SEF-FORM\GETArray" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-05-HREF-SEF-FORM\SEFForController" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-05-HREF-SEF-FORM\SEFForMethod" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-05-HREF-SEF-FORM\URIWithParamFromInput" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-05-HREF-SEF-FORM\URIWithTemplateSetVar" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-06-Templates\Creator-PHP-PHPShort-Twig" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-06-Templates\OneKeyForAllURLTemplates" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-06-Templates\SetTemplateByMethodAndAJAXType" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-06-Templates\Template-engine-Smarty" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-06-Templates\Template-engine-Twig" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-07-PHPUnitTest-UML\FrozenDataForDebug" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-07-PHPUnitTest-UML\PHPUnitTestGenerator" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-07-PHPUnitTest-UML\UML2Models" "en"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-07-PHPUnitTest-UML\VisualTestGenerator" "en"