reset
if [ -n $1 ]; then
	lang=$1/
else
	lang=""
fi
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorld" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorldConfig")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorldifParamHello")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorldParamDiff")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorldYAML")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-02-jQuery-AJAX-Extend-Parents/CallAJAXParent")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-02-jQuery-AJAX-Extend-Parents/jQueryAJAXAnchorNavigation")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-02-jQuery-AJAX-Extend-Parents/ThisAndExtendController")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-03-API=MySQL-Bitrix-Joomla/BitrixAPI" "bitrix/modules/evnine/classes/general/")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-03-API=MySQL-Bitrix-Joomla/BitrixAPITwig" "bitrix/modules/evnine/classes/general/")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-03-API=MySQL-Bitrix-Joomla/JoomlaAPI")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-03-API=MySQL-Bitrix-Joomla/MySQL")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-04-Validation-Errors-ExceptionThrow/ModelsMSGErrors")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-04-Validation-Errors-ExceptionThrow/ModelsMSGExceptionThrowError")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-04-Validation-Errors-ExceptionThrow/ModelsMSGInfo")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-04-Validation-Errors-ExceptionThrow/Validation")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/ExtendController-Method")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/Form")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/FormMultiMethodSumbit")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/GETArray")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/SEFForController")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/SEFForMethod")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/URIWithParamFromInput")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/URIWithTemplateSetVar")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/Creator-PHP-PHPShort-Twig")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/OneKeyForAllURLTemplates")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/SetTemplateByMethodAndAJAXType")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/Template-engine-Smarty")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/Template-engine-Twig")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-07-PHPUnitTest-UML/FrozenDataForDebug")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-07-PHPUnitTest-UML/PHPUnitTestGenerator")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-07-PHPUnitTest-UML/UML2Models")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-07-PHPUnitTest-UML/VisualTestGenerator")