cls
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-01-Hello-World\HelloWorld" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-01-Hello-World\HelloWorldConfig" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-01-Hello-World\HelloWorldifParamHello" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-01-Hello-World\HelloWorldParamDiff" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-01-Hello-World\HelloWorldYAML" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-02-jQuery-AJAX-Extend-Parents\CallAJAXParent" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-02-jQuery-AJAX-Extend-Parents\jQueryAJAXAnchorNavigation" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-02-jQuery-AJAX-Extend-Parents\ThisAndExtendController" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-03-API=MySQL-Bitrix-Joomla\BitrixAPI" "ru" "bitrix\modules\evnine\classes\general\"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-03-API=MySQL-Bitrix-Joomla\BitrixAPITwig" "ru" "bitrix\modules\evnine\classes\general\"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-03-API=MySQL-Bitrix-Joomla\JoomlaAPI" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-03-API=MySQL-Bitrix-Joomla\MySQL" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-04-Validation-Errors-ExceptionThrow\ModelsMSGErrors" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-04-Validation-Errors-ExceptionThrow\ModelsMSGExceptionThrowError" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-04-Validation-Errors-ExceptionThrow\ModelsMSGInfo" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-04-Validation-Errors-ExceptionThrow\Validation" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-05-HREF-SEF-FORM\ExtendController-Method" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-05-HREF-SEF-FORM\Form" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-05-HREF-SEF-FORM\FormMultiMethodSumbit" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-05-HREF-SEF-FORM\GETArray" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-05-HREF-SEF-FORM\SEFForController" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-05-HREF-SEF-FORM\SEFForMethod" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-05-HREF-SEF-FORM\URIWithParamFromInput" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-05-HREF-SEF-FORM\URIWithTemplateSetVar" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-06-Templates\Creator-PHP-PHPShort-Twig" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-06-Templates\OneKeyForAllURLTemplates" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-06-Templates\SetTemplateByMethodAndAJAXType" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-06-Templates\Template-engine-Smarty" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-06-Templates\Template-engine-Twig" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-07-PHPUnitTest-UML\FrozenDataForDebug" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-07-PHPUnitTest-UML\PHPUnitTestGenerator" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-07-PHPUnitTest-UML\UML2Models" "ru"
call Source\update-script\update-lessons-from-source-script.cmd "evnine-lesson-07-PHPUnitTest-UML\VisualTestGenerator" "ru"