reset
if [ -n $1 ]; then
	lang=$1/
else
	lang=""
fi
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorld" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorldConfig" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorldifParamHello" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorldParamDiff" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorldYAML" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-02-jQuery-AJAX-Extend-Parents/CallAJAXParent" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-02-jQuery-AJAX-Extend-Parents/jQueryAJAXAnchorNavigation" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-02-jQuery-AJAX-Extend-Parents/ThisAndExtendController" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-03-API=MySQL-Bitrix-Joomla/BitrixAPI" "bitrix/modules/evnine/classes/general/" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-03-API=MySQL-Bitrix-Joomla/BitrixAPITwig" "bitrix/modules/evnine/classes/general/" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-03-API=MySQL-Bitrix-Joomla/JoomlaAPI" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-03-API=MySQL-Bitrix-Joomla/MySQL" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-04-Validation-Errors-ExceptionThrow/ModelsMSGErrors" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-04-Validation-Errors-ExceptionThrow/ModelsMSGExceptionThrowError" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-04-Validation-Errors-ExceptionThrow/ModelsMSGInfo" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-04-Validation-Errors-ExceptionThrow/Validation" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/ExtendController-Method" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/Form" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/FormMultiMethodSumbit" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/GETArray" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/SEFForController" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/SEFForMethod" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/URIWithParamFromInput" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/URIWithTemplateSetVar" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/Creator-PHP-PHPShort-Twig" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/OneKeyForAllURLTemplates" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/SetTemplateByMethodAndAJAXType" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/Template-engine-Smarty" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/Template-engine-Twig" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-07-PHPUnitTest-UML/FrozenDataForDebug" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-07-PHPUnitTest-UML/PHPUnitTestGenerator" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-07-PHPUnitTest-UML/UML2Models" ${lang})
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-07-PHPUnitTest-UML/VisualTestGenerator" ${lang})