reset
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorld" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorldConfig" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorldifParamHello" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorldParamDiff" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorldYAML" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-02-jQuery-AJAX-Extend-Parents/CallAJAXParent" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-02-jQuery-AJAX-Extend-Parents/jQueryAJAXAnchorNavigation" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-02-jQuery-AJAX-Extend-Parents/ThisAndExtendController" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-03-API=MySQL-Bitrix-Joomla/BitrixAPI" "ru" "bitrix/modules/evnine/classes/general/")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-03-API=MySQL-Bitrix-Joomla/BitrixAPITwig" "ru" "bitrix/modules/evnine/classes/general/")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-03-API=MySQL-Bitrix-Joomla/JoomlaAPI" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-03-API=MySQL-Bitrix-Joomla/MySQL" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-04-Validation-Errors-ExceptionThrow/ModelsMSGErrors" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-04-Validation-Errors-ExceptionThrow/ModelsMSGExceptionThrowError" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-04-Validation-Errors-ExceptionThrow/ModelsMSGInfo" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-04-Validation-Errors-ExceptionThrow/Validation" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/ExtendController-Method" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/Form" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/FormMultiMethodSumbit" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/GETArray" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/SEFForController" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/SEFForMethod" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/URIWithParamFromInput" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/URIWithTemplateSetVar" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/Creator-PHP-PHPShort-Twig" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/OneKeyForAllURLTemplates" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/SetTemplateByMethodAndAJAXType" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/Template-engine-Smarty" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/Template-engine-Twig" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-07-PHPUnitTest-UML/FrozenDataForDebug" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-07-PHPUnitTest-UML/PHPUnitTestGenerator" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-07-PHPUnitTest-UML/UML2Models" "ru")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-07-PHPUnitTest-UML/VisualTestGenerator" "ru")