reset
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorld" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorldConfig" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorldifParamHello" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorldParamDiff" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-01-Hello-World/HelloWorldYAML" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-02-jQuery-AJAX-Extend-Parents/CallAJAXParent" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-02-jQuery-AJAX-Extend-Parents/jQueryAJAXAnchorNavigation" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-02-jQuery-AJAX-Extend-Parents/ThisAndExtendController" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-03-API=MySQL-Bitrix-Joomla/BitrixAPI" "en" "bitrix/modules/evnine/classes/general/")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-03-API=MySQL-Bitrix-Joomla/BitrixAPITwig" "en" "bitrix/modules/evnine/classes/general/")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-03-API=MySQL-Bitrix-Joomla/JoomlaAPI" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-03-API=MySQL-Bitrix-Joomla/MySQL" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-04-Validation-Errors-ExceptionThrow/ModelsMSGErrors" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-04-Validation-Errors-ExceptionThrow/ModelsMSGExceptionThrowError" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-04-Validation-Errors-ExceptionThrow/ModelsMSGInfo" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-04-Validation-Errors-ExceptionThrow/Validation" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/ExtendController-Method" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/Form" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/FormMultiMethodSumbit" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/GETArray" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/SEFForController" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/SEFForMethod" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/URIWithParamFromInput" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-05-HREF-SEF-FORM/URIWithTemplateSetVar" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/Creator-PHP-PHPShort-Twig" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/OneKeyForAllURLTemplates" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/SetTemplateByMethodAndAJAXType" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/Template-engine-Smarty" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-06-Templates/Template-engine-Twig" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-07-PHPUnitTest-UML/FrozenDataForDebug" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-07-PHPUnitTest-UML/PHPUnitTestGenerator" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-07-PHPUnitTest-UML/UML2Models" "en")
$(./Source/update-script/update-lessons-from-source-script.sh "evnine-lesson-07-PHPUnitTest-UML/VisualTestGenerator" "en")