<?php

require_once 'evninePHPUnit.php';

/**
 * Test class for evninePHPUnit.
 * Generated by PHPUnit on 2011-09-23 at 22:01:13.
 */
class evninePHPUnitTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var evninePHPUnit
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new evninePHPUnit;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert ('getControllerForParam_validation_default_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'default', 'ajax'=>'false'))).
     */
    public function testGetControllerForParam_validation_default_Test()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'default', 'ajax'=>'false'))),
          $this->object->getControllerForParam_validation_default_Test('getControllerForParam_validation_default_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_validation_default_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'default', 'ajax'=>'true'))).
     */
    public function testGetControllerForParam_validation_default_Test2()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'default', 'ajax'=>'true'))),
          $this->object->getControllerForParam_validation_default_Test('getControllerForParam_validation_default_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_validation_submit_1_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'submit_1', 'ajax'=>'false'))).
     */
    public function testGetControllerForParam_validation_submit_1_Test()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'submit_1', 'ajax'=>'false'))),
          $this->object->getControllerForParam_validation_submit_1_Test('getControllerForParam_validation_submit_1_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_validation_submit_1_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'submit_1', 'ajax'=>'true'))).
     */
    public function testGetControllerForParam_validation_submit_1_Test2()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'submit_1', 'ajax'=>'true'))),
          $this->object->getControllerForParam_validation_submit_1_Test('getControllerForParam_validation_submit_1_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_validation_submit_2_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'submit_2', 'ajax'=>'false'))).
     */
    public function testGetControllerForParam_validation_submit_2_Test()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'submit_2', 'ajax'=>'false'))),
          $this->object->getControllerForParam_validation_submit_2_Test('getControllerForParam_validation_submit_2_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_validation_submit_2_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'submit_2', 'ajax'=>'true'))).
     */
    public function testGetControllerForParam_validation_submit_2_Test2()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'submit_2', 'ajax'=>'true'))),
          $this->object->getControllerForParam_validation_submit_2_Test('getControllerForParam_validation_submit_2_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_validation_submit_3_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'submit_3', 'ajax'=>'false'))).
     */
    public function testGetControllerForParam_validation_submit_3_Test()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'submit_3', 'ajax'=>'false'))),
          $this->object->getControllerForParam_validation_submit_3_Test('getControllerForParam_validation_submit_3_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_validation_submit_3_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'submit_3', 'ajax'=>'true'))).
     */
    public function testGetControllerForParam_validation_submit_3_Test2()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'submit_3', 'ajax'=>'true'))),
          $this->object->getControllerForParam_validation_submit_3_Test('getControllerForParam_validation_submit_3_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_validation_submit_4_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'submit_4', 'ajax'=>'false'))).
     */
    public function testGetControllerForParam_validation_submit_4_Test()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'submit_4', 'ajax'=>'false'))),
          $this->object->getControllerForParam_validation_submit_4_Test('getControllerForParam_validation_submit_4_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_validation_submit_4_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'submit_4', 'ajax'=>'true'))).
     */
    public function testGetControllerForParam_validation_submit_4_Test2()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'validation', 'method'=>'submit_4', 'ajax'=>'true'))),
          $this->object->getControllerForParam_validation_submit_4_Test('getControllerForParam_validation_submit_4_Test',$array,$param)
        );
    }
}
?>
