<?php

require_once 'evninePHPUnit.php';

/**
 * Test class for evninePHPUnit.
 * Generated by PHPUnit on 2011-09-24 at 13:21:19.
 */
class evninePHPUnitTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var evninePHPUnit
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new evninePHPUnit;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert ('getControllerForParam_helloworld_default_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default', 'debug'=>'false', 'all'=>'all', 'REQUEST'=>array( 'test1'=>'1', 'test'=>'23'), 'PHPFlag'=>''))).
     */
    public function testGetControllerForParam_helloworld_default_Test()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default', 'debug'=>'false', 'all'=>'all', 'REQUEST'=>array( 'test1'=>'1', 'test'=>'23'), 'PHPFlag'=>''))),
          $this->object->getControllerForParam_helloworld_default_Test('getControllerForParam_helloworld_default_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_helloworld_default_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default', 'debug'=>'false', 'all'=>'all', 'REQUEST'=>array( 'test2'=>'1'), 'PHPFlag'=>''))).
     */
    public function testGetControllerForParam_helloworld_default_Test2()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default', 'debug'=>'false', 'all'=>'all', 'REQUEST'=>array( 'test2'=>'1'), 'PHPFlag'=>''))),
          $this->object->getControllerForParam_helloworld_default_Test('getControllerForParam_helloworld_default_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_helloworld_default2_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default2', 'debug'=>'false', 'all'=>'all', 'REQUEST'=>array( 'test_id'=>'1')))).
     */
    public function testGetControllerForParam_helloworld_default2_Test()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default2', 'debug'=>'false', 'all'=>'all', 'REQUEST'=>array( 'test_id'=>'1')))),
          $this->object->getControllerForParam_helloworld_default2_Test('getControllerForParam_helloworld_default2_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_helloworld_default_no_inURLUnitTest_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default_no_inURLUnitTest', 'debug'=>'false', 'all'=>'all', 'REQUEST'=>array( 'test_id'=>'1')))).
     */
    public function testGetControllerForParam_helloworld_default_no_inURLUnitTest_Test()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default_no_inURLUnitTest', 'debug'=>'false', 'all'=>'all', 'REQUEST'=>array( 'test_id'=>'1')))),
          $this->object->getControllerForParam_helloworld_default_no_inURLUnitTest_Test('getControllerForParam_helloworld_default_no_inURLUnitTest_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_param_gen_models_default_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'param_gen_models', 'method'=>'default', 'debug'=>''))).
     */
    public function testGetControllerForParam_param_gen_models_default_Test()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'param_gen_models', 'method'=>'default', 'debug'=>''))),
          $this->object->getControllerForParam_param_gen_models_default_Test('getControllerForParam_param_gen_models_default_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_param_gen_models_reset_phpunit_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'param_gen_models', 'method'=>'reset_phpunit', 'debug'=>''))).
     */
    public function testGetControllerForParam_param_gen_models_reset_phpunit_Test()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'param_gen_models', 'method'=>'reset_phpunit', 'debug'=>''))),
          $this->object->getControllerForParam_param_gen_models_reset_phpunit_Test('getControllerForParam_param_gen_models_reset_phpunit_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_param_gen_view_default_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'param_gen_view', 'method'=>'default', 'debug'=>''))).
     */
    public function testGetControllerForParam_param_gen_view_default_Test()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'param_gen_view', 'method'=>'default', 'debug'=>''))),
          $this->object->getControllerForParam_param_gen_view_default_Test('getControllerForParam_param_gen_view_default_Test',$array,$param)
        );
    }
}
?>
