<?php

require_once 'evninePHPUnit.php';

/**
 * Test class for evninePHPUnit.
 * Generated by PHPUnit on 2011-09-23 at 21:45:56.
 */
class evninePHPUnitTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var evninePHPUnit
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new evninePHPUnit;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert ('getControllerForParam_helloworld_default_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default', 'ajax'=>'false'))).
     */
    public function testGetControllerForParam_helloworld_default_Test()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default', 'ajax'=>'false'))),
          $this->object->getControllerForParam_helloworld_default_Test('getControllerForParam_helloworld_default_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_helloworld_default_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default', 'ajax'=>'true'))).
     */
    public function testGetControllerForParam_helloworld_default_Test2()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default', 'ajax'=>'true'))),
          $this->object->getControllerForParam_helloworld_default_Test('getControllerForParam_helloworld_default_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_helloworldparent_default_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworldparent', 'method'=>'default', 'ajax'=>'false'))).
     */
    public function testGetControllerForParam_helloworldparent_default_Test()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworldparent', 'method'=>'default', 'ajax'=>'false'))),
          $this->object->getControllerForParam_helloworldparent_default_Test('getControllerForParam_helloworldparent_default_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_helloworldparent_default_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworldparent', 'method'=>'default', 'ajax'=>'true'))).
     */
    public function testGetControllerForParam_helloworldparent_default_Test2()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworldparent', 'method'=>'default', 'ajax'=>'true'))),
          $this->object->getControllerForParam_helloworldparent_default_Test('getControllerForParam_helloworldparent_default_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_helloworldparentparent_default_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworldparentparent', 'method'=>'default', 'ajax'=>'false'))).
     */
    public function testGetControllerForParam_helloworldparentparent_default_Test()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworldparentparent', 'method'=>'default', 'ajax'=>'false'))),
          $this->object->getControllerForParam_helloworldparentparent_default_Test('getControllerForParam_helloworldparentparent_default_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_helloworldparentparent_default_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworldparentparent', 'method'=>'default', 'ajax'=>'true'))).
     */
    public function testGetControllerForParam_helloworldparentparent_default_Test2()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworldparentparent', 'method'=>'default', 'ajax'=>'true'))),
          $this->object->getControllerForParam_helloworldparentparent_default_Test('getControllerForParam_helloworldparentparent_default_Test',$array,$param)
        );
    }
}
?>
