<?php

require_once 'evninePHPUnit.php';

/**
 * Test class for evninePHPUnit.
 * Generated by PHPUnit on 2011-09-24 at 09:35:57.
 */
class evninePHPUnitTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var evninePHPUnit
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new evninePHPUnit;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert ('getControllerForParam_helloworld_default_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default', 'for_all'=>'all', 'REQUEST'=>array( 'test1'=>'1', 'test3'=>'23')))).
     */
    public function testGetControllerForParam_helloworld_default_Test()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default', 'for_all'=>'all', 'REQUEST'=>array( 'test1'=>'1', 'test3'=>'23')))),
          $this->object->getControllerForParam_helloworld_default_Test('getControllerForParam_helloworld_default_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_helloworld_default_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default', 'for_all'=>'all', 'REQUEST'=>array( 'test2'=>'1')))).
     */
    public function testGetControllerForParam_helloworld_default_Test2()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default', 'for_all'=>'all', 'REQUEST'=>array( 'test2'=>'1')))),
          $this->object->getControllerForParam_helloworld_default_Test('getControllerForParam_helloworld_default_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_helloworld_default_no_inURLUnitTest_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default_no_inURLUnitTest', 'for_all'=>'all'))).
     */
    public function testGetControllerForParam_helloworld_default_no_inURLUnitTest_Test()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'helloworld', 'method'=>'default_no_inURLUnitTest', 'for_all'=>'all'))),
          $this->object->getControllerForParam_helloworld_default_no_inURLUnitTest_Test('getControllerForParam_helloworld_default_no_inURLUnitTest_Test',$array,$param)
        );
    }

    /**
     * Generated from @assert ('getControllerForParam_self_php_unit_test_default_Test',$array,$param) == $array=($this->object->getControllerForParam($param=array( 'controller'=>'self_php_unit_test', 'method'=>'default'))).
     */
    public function testGetControllerForParam_self_php_unit_test_default_Test()
    {
        $this->assertEquals(
          $array=($this->object->getControllerForParam($param=array( 'controller'=>'self_php_unit_test', 'method'=>'default'))),
          $this->object->getControllerForParam_self_php_unit_test_default_Test('getControllerForParam_self_php_unit_test_default_Test',$array,$param)
        );
    }
}
?>
